/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_teradata_jni_CptJni */

#ifndef _Included_com_teradata_jni_CptJni
#define _Included_com_teradata_jni_CptJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_teradata_jni_CptJni
 * Method:    encrypt
 * Signature: ([BJB)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_teradata_jni_CptJni_encrypt
  (JNIEnv *, jclass, jbyteArray, jlong, jbyte);

/*
 * Class:     com_teradata_jni_CptJni
 * Method:    decrypt
 * Signature: ([BJB)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_teradata_jni_CptJni_decrypt
  (JNIEnv *, jclass, jbyteArray, jlong, jbyte);

#ifdef __cplusplus
}
#endif
#endif
