/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_teradata_jni_CptJni */

#ifndef _Included_com_teradata_jni_CptJni
#define _Included_com_teradata_jni_CptJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_teradata_jni_CptJni
 * Method:    encrypt
 * Signature: ([BJB)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_teradata_jni_CptJni_encrypt
  (JNIEnv *, jclass, jbyteArray, jlong, jbyte);

/*
 * Class:     com_teradata_jni_CptJni
 * Method:    decrypt
 * Signature: ([BJB)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_teradata_jni_CptJni_decrypt
  (JNIEnv *, jclass, jbyteArray, jlong, jbyte);

/*
 * Class:     com_teradata_jni_CptJni
 * Method:    multiSubPolicyEncrypt
 * Signature: ([BLcom/teradata/jni/Policy;JB)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_teradata_jni_CptJni_multiSubPolicyEncrypt
  (JNIEnv *, jclass, jbyteArray, jobject, jlong, jbyte);

/*
 * Class:     com_teradata_jni_CptJni
 * Method:    multiSubPolicyDecrypt
 * Signature: ([BLcom/teradata/jni/Policy;JB)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_teradata_jni_CptJni_multiSubPolicyDecrypt
  (JNIEnv *, jclass, jbyteArray, jobject, jlong, jbyte);

#ifdef __cplusplus
}
#endif
#endif
